baseURL = "https://otagomohio.github.io/hacky2021/"
languageCode = "en-us"
title = "Hacky Hour 2021"
# add theme
theme = "hugo-theme-learn"

# disable table of contents
disableToc = "true"

# for search functionality
[outputs]
    home = [ "HTML", "RSS", "JSON"]

#publishDir = "docs"

## learn website-specific params
[params]
    author = "Hugh Cross"
    themeVariant = "green"
    disableLandingPageButton = true
    landingPageURL = "/hacky2021/"

[markup.goldmark.renderer]
    unsafe=true
    